dist: xenial
language: java

jdk:
  - openjdk11

# disable shallow clone so SonarCloud can use SCM history to compute blame data
git:
  depth: false

# the first part of the cache phase happens
# between git checkout and before_install
cache:
  directories:
    - $HOME/.m2/repository

# the default java install step does
# mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install:
  - mvn install -DskipTests=true -B -V -Psource-quality

# before_cache happens before the second part of the cache phase,
# which happens after script
before_cache:
  - rm -rf $HOME/.m2/repository/io/lighty


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.branch.name=$TRAVIS_BRANCH -Dsonar.host.url=https://sonarcloud.io; fi
